// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvtUekyrzF9hs04VEiGYZqqBR-0axgtgY',
    appId: '1:174270203695:web:e5a5c40adbe800466e83da',
    messagingSenderId: '174270203695',
    projectId: 'employee-db-779c3',
    authDomain: 'employee-db-779c3.firebaseapp.com',
    databaseURL: 'https://employee-db-779c3-default-rtdb.firebaseio.com',
    storageBucket: 'employee-db-779c3.firebasestorage.app',
    measurementId: 'G-WG1VE8H4L0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF-KVskwPa49OCmMpEGWVciDKRCpqFLlE',
    appId: '1:174270203695:android:3e0a46f50799996e6e83da',
    messagingSenderId: '174270203695',
    projectId: 'employee-db-779c3',
    databaseURL: 'https://employee-db-779c3-default-rtdb.firebaseio.com',
    storageBucket: 'employee-db-779c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABkC9qwJYGW-jpOldslBdiQg5pLKwEUXo',
    appId: '1:174270203695:ios:25fc8734945aa4d76e83da',
    messagingSenderId: '174270203695',
    projectId: 'employee-db-779c3',
    databaseURL: 'https://employee-db-779c3-default-rtdb.firebaseio.com',
    storageBucket: 'employee-db-779c3.firebasestorage.app',
    iosBundleId: 'com.example.employeeMseptiawan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABkC9qwJYGW-jpOldslBdiQg5pLKwEUXo',
    appId: '1:174270203695:ios:25fc8734945aa4d76e83da',
    messagingSenderId: '174270203695',
    projectId: 'employee-db-779c3',
    databaseURL: 'https://employee-db-779c3-default-rtdb.firebaseio.com',
    storageBucket: 'employee-db-779c3.firebasestorage.app',
    iosBundleId: 'com.example.employeeMseptiawan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvtUekyrzF9hs04VEiGYZqqBR-0axgtgY',
    appId: '1:174270203695:web:5ab09ff2f293165c6e83da',
    messagingSenderId: '174270203695',
    projectId: 'employee-db-779c3',
    authDomain: 'employee-db-779c3.firebaseapp.com',
    databaseURL: 'https://employee-db-779c3-default-rtdb.firebaseio.com',
    storageBucket: 'employee-db-779c3.firebasestorage.app',
    measurementId: 'G-4YVLYVSQ1Y',
  );
}
